### ISSUE TITLE
pwm pins exhibit bimodal behavior

### ISSUE THREAD

**Issue by mwhooker** [pcduino/python-pcduino#4]
Edit: see below for how to reproduce

Sometimes a PWM pin will get in to a mode where values
0: off
1: <some arbitrary intensity>
2: <same as 1>

i.e. setting a value >= 1 will cause it to emit at a certain frequency (I've seen low values and high values), but no value > 1 will change it.

The actual value written can still be read.

Rebooting the device fixes the issue.

**Comment by labixiaohu** [comment]
The following error occurred while I was editing my project: No such file or directory :/sys/class/misc/pwmtimer/enable
